### ISSUE TITLE
Group Sync Permission Bug [Solution]

### ISSUE THREAD

**Issue by IsS127** [NamelessMC/Nameless-Plugin#38]
Known bug, while doing ur group sync permissions all OP get the permission ofc,
TO FIX you do a minus permission in ur permissions manager.

**Comment by IsS127** [comment]
Fixed bug in https://github.com/NamelessMC/Nameless-Plugin/commit/d909f009133e61826d8a145a7b88297439e09411

**Comment by IsS127** [comment]
Also fixed at https://github.com/NamelessMC/Nameless-Plugin/commit/60d90400a1ae1bcf9216480c5b7506449dcf69f2

**Comment by Skizzy77** [comment]
This did not fix the issue for me. Also - non op players groups don't update on the website..
